import type * as React from "react"

import {
  AlertDemo,
  AvatarDemo,
  BadgeDemo,
  ButtonDemo,
  InputDemo,
  LabelDemo,
  SeparatorDemo,
  SkeletonDemo,
} from "@www/components/demos/basics"
import {
  CalendarDemo,
  CheckboxDemo,
  ComboboxDemo,
  DatePickerDemo,
  FormDemo,
  InputOTPDemo,
  ProgressDemo,
  RadioGroupDemo,
  SelectDemo,
  SliderDemo,
  SwitchDemo,
  TextareaDemo,
  ToggleDemo,
  ToggleGroupDemo,
} from "@www/components/demos/forms"
import {
  AlertDialogDemo,
  CommandDemo,
  ContextMenuDemo,
  DialogDemo,
  DrawerDemo,
  DropdownMenuDemo,
  HoverCardDemo,
  MenubarDemo,
  PopoverDemo,
  SheetDemo,
  SonnerDemo,
  TooltipDemo,
} from "@www/components/demos/overlays"
import {
  AccordionDemo,
  BreadcrumbDemo,
  CardDemo,
  CollapsibleDemo,
  PaginationDemo,
  ScrollAreaDemo,
  TableDemo,
  TabsDemo,
} from "@www/components/demos/structure"
import {
  CtaDemo,
  FaqDemo,
  FeaturesDemo,
  FooterDemo,
  HeroDemo,
  NavbarDemo,
  PricingDemo,
  StatsDemo,
  TestimonialsDemo,
} from "@www/components/demos/blocks"
import {
  AspectRatioDemo,
  CarouselDemo,
  ChartDemo,
  DataTableDemo,
  NavigationMenuDemo,
  ResizableDemo,
  SidebarDemo,
  TypographyDemo,
} from "@www/components/demos/batch9"
import {
  CalloutDemo,
  DataListDemo,
  KbdDemo,
  QuoteDemo,
  SegmentedControlDemo,
  SpinnerDemo,
} from "@www/components/demos/batch10"
import {
  InteractiveHoverButtonDemo,
  MagicCardDemo,
  NeonGradientCardDemo,
  PulsatingButtonDemo,
  RainbowButtonDemo,
  RippleButtonDemo,
  ShimmerButtonDemo,
  ShineBorderDemo,
} from "@www/components/demos/batch11"
import {
  AnimatedBeamDemo,
  AnimatedListDemo,
  AvatarCirclesDemo,
  BentoGridDemo,
  BorderBeamDemo,
  ConfettiDemo,
  DockDemo,
  MeteorsDemo,
  OrbitingCirclesDemo,
  ParticlesDemo,
} from "@www/components/demos/batch12"
import {
  AuroraTextDemo,
  BoxRevealDemo,
  FileTreeDemo,
  HeroVideoDialogDemo,
  MorphingTextDemo,
  ScrollBasedVelocityDemo,
  ScrollProgressDemo,
  SparklesTextDemo,
  TerminalDemo,
  TextRevealDemo,
} from "@www/components/demos/batch13"
import {
  BlurTextDemo,
  CircularTextDemo,
  CurvedLoopDemo,
  DecryptedTextDemo,
  GlitchTextDemo,
  ScrambleTextDemo,
  SplitTextDemo,
  VariableProximityDemo,
} from "@www/components/demos/batch14"
import {
  BlobCursorDemo,
  ClickSparkDemo,
  InfiniteScrollDemo,
  MagnetDemo,
  MasonryDemo,
  PixelTrailDemo,
  StackDemo,
  StarBorderDemo,
  StepperDemo,
  TiltedCardDemo,
} from "@www/components/demos/batch15"
import {
  AuroraDemo,
  DotPatternDemo,
  GlobeDemo,
  GridPatternDemo,
  HyperspeedDemo,
  RetroGridDemo,
  RippleDemo,
  WavesDemo,
} from "@www/components/demos/batch16"
import {
  AnimatedGradientDemo,
  CountUpDemo,
  FadeInDemo,
  MarqueeDemo,
  ShimmerDemo,
  TypewriterDemo,
} from "@www/components/demos/motion"

/** Registry item name → live demo rendered on its docs page. */
export const demos: Record<string, React.ComponentType> = {
  accordion: AccordionDemo,
  alert: AlertDemo,
  "alert-dialog": AlertDialogDemo,
  avatar: AvatarDemo,
  badge: BadgeDemo,
  breadcrumb: BreadcrumbDemo,
  button: ButtonDemo,
  calendar: CalendarDemo,
  card: CardDemo,
  checkbox: CheckboxDemo,
  collapsible: CollapsibleDemo,
  combobox: ComboboxDemo,
  command: CommandDemo,
  "context-menu": ContextMenuDemo,
  "date-picker": DatePickerDemo,
  dialog: DialogDemo,
  drawer: DrawerDemo,
  "dropdown-menu": DropdownMenuDemo,
  form: FormDemo,
  "hover-card": HoverCardDemo,
  input: InputDemo,
  "input-otp": InputOTPDemo,
  label: LabelDemo,
  menubar: MenubarDemo,
  pagination: PaginationDemo,
  popover: PopoverDemo,
  progress: ProgressDemo,
  "radio-group": RadioGroupDemo,
  "scroll-area": ScrollAreaDemo,
  select: SelectDemo,
  separator: SeparatorDemo,
  sheet: SheetDemo,
  skeleton: SkeletonDemo,
  slider: SliderDemo,
  sonner: SonnerDemo,
  switch: SwitchDemo,
  table: TableDemo,
  tabs: TabsDemo,
  textarea: TextareaDemo,
  toggle: ToggleDemo,
  "toggle-group": ToggleGroupDemo,
  tooltip: TooltipDemo,
  "aspect-ratio": AspectRatioDemo,
  carousel: CarouselDemo,
  chart: ChartDemo,
  "data-table": DataTableDemo,
  "navigation-menu": NavigationMenuDemo,
  resizable: ResizableDemo,
  sidebar: SidebarDemo,
  typography: TypographyDemo,
  callout: CalloutDemo,
  "data-list": DataListDemo,
  kbd: KbdDemo,
  quote: QuoteDemo,
  "segmented-control": SegmentedControlDemo,
  spinner: SpinnerDemo,
  "shimmer-button": ShimmerButtonDemo,
  "rainbow-button": RainbowButtonDemo,
  "pulsating-button": PulsatingButtonDemo,
  "ripple-button": RippleButtonDemo,
  "interactive-hover-button": InteractiveHoverButtonDemo,
  "magic-card": MagicCardDemo,
  "neon-gradient-card": NeonGradientCardDemo,
  "bento-grid": BentoGridDemo,
  "avatar-circles": AvatarCirclesDemo,
  dock: DockDemo,
  "hero-video-dialog": HeroVideoDialogDemo,
  terminal: TerminalDemo,
  "file-tree": FileTreeDemo,
  "tilted-card": TiltedCardDemo,
  stack: StackDemo,
  stepper: StepperDemo,
  masonry: MasonryDemo,
  "dot-pattern": DotPatternDemo,
  "grid-pattern": GridPatternDemo,
}

/** Registry block name → live demo rendered full-width on its docs page. */
export const blockDemos: Record<string, React.ComponentType> = {
  cta: CtaDemo,
  faq: FaqDemo,
  features: FeaturesDemo,
  footer: FooterDemo,
  hero: HeroDemo,
  navbar: NavbarDemo,
  pricing: PricingDemo,
  stats: StatsDemo,
  testimonials: TestimonialsDemo,
}

/** Registry motion name → live demo rendered on its docs page. */
export const motionDemos: Record<string, React.ComponentType> = {
  "animated-gradient": AnimatedGradientDemo,
  "count-up": CountUpDemo,
  "fade-in": FadeInDemo,
  marquee: MarqueeDemo,
  "shine-border": ShineBorderDemo,
  "border-beam": BorderBeamDemo,
  "animated-beam": AnimatedBeamDemo,
  "animated-list": AnimatedListDemo,
  confetti: ConfettiDemo,
  meteors: MeteorsDemo,
  "orbiting-circles": OrbitingCirclesDemo,
  particles: ParticlesDemo,
  shimmer: ShimmerDemo,
  typewriter: TypewriterDemo,
  "text-reveal": TextRevealDemo,
  "box-reveal": BoxRevealDemo,
  "sparkles-text": SparklesTextDemo,
  "morphing-text": MorphingTextDemo,
  "aurora-text": AuroraTextDemo,
  "scroll-progress": ScrollProgressDemo,
  "scroll-based-velocity": ScrollBasedVelocityDemo,
  "split-text": SplitTextDemo,
  "blur-text": BlurTextDemo,
  "decrypted-text": DecryptedTextDemo,
  "scramble-text": ScrambleTextDemo,
  "circular-text": CircularTextDemo,
  "curved-loop": CurvedLoopDemo,
  "variable-proximity": VariableProximityDemo,
  "glitch-text": GlitchTextDemo,
  "click-spark": ClickSparkDemo,
  magnet: MagnetDemo,
  "star-border": StarBorderDemo,
  "pixel-trail": PixelTrailDemo,
  "blob-cursor": BlobCursorDemo,
  "infinite-scroll": InfiniteScrollDemo,
  "retro-grid": RetroGridDemo,
  ripple: RippleDemo,
  aurora: AuroraDemo,
  hyperspeed: HyperspeedDemo,
  waves: WavesDemo,
  globe: GlobeDemo,
}
