import type * as React from "react"

import {
  AlertDemo,
  AvatarDemo,
  BadgeDemo,
  ButtonDemo,
  InputDemo,
  LabelDemo,
  SeparatorDemo,
  SkeletonDemo,
} from "@www/components/demos/basics"
import {
  CalendarDemo,
  CheckboxDemo,
  ComboboxDemo,
  DatePickerDemo,
  FormDemo,
  ProgressDemo,
  RadioGroupDemo,
  SelectDemo,
  SliderDemo,
  SwitchDemo,
  ToggleDemo,
} from "@www/components/demos/forms"
import {
  AlertDialogDemo,
  CommandDemo,
  ContextMenuDemo,
  DialogDemo,
  DropdownMenuDemo,
  HoverCardDemo,
  PopoverDemo,
  SheetDemo,
  SonnerDemo,
  TooltipDemo,
} from "@www/components/demos/overlays"
import {
  AccordionDemo,
  BreadcrumbDemo,
  CardDemo,
  CollapsibleDemo,
  PaginationDemo,
  TableDemo,
  TabsDemo,
} from "@www/components/demos/structure"

/** Registry item name → live demo rendered on its docs page. */
export const demos: Record<string, React.ComponentType> = {
  accordion: AccordionDemo,
  alert: AlertDemo,
  "alert-dialog": AlertDialogDemo,
  avatar: AvatarDemo,
  badge: BadgeDemo,
  breadcrumb: BreadcrumbDemo,
  button: ButtonDemo,
  calendar: CalendarDemo,
  card: CardDemo,
  checkbox: CheckboxDemo,
  collapsible: CollapsibleDemo,
  combobox: ComboboxDemo,
  command: CommandDemo,
  "context-menu": ContextMenuDemo,
  "date-picker": DatePickerDemo,
  dialog: DialogDemo,
  "dropdown-menu": DropdownMenuDemo,
  form: FormDemo,
  "hover-card": HoverCardDemo,
  input: InputDemo,
  label: LabelDemo,
  pagination: PaginationDemo,
  popover: PopoverDemo,
  progress: ProgressDemo,
  "radio-group": RadioGroupDemo,
  select: SelectDemo,
  separator: SeparatorDemo,
  sheet: SheetDemo,
  skeleton: SkeletonDemo,
  slider: SliderDemo,
  sonner: SonnerDemo,
  switch: SwitchDemo,
  table: TableDemo,
  tabs: TabsDemo,
  toggle: ToggleDemo,
  tooltip: TooltipDemo,
}
