import type * as React from "react"

import {
  AlertDemo,
  AvatarDemo,
  BadgeDemo,
  ButtonDemo,
  InputDemo,
  LabelDemo,
  SeparatorDemo,
  SkeletonDemo,
} from "@www/components/demos/basics"
import {
  CalendarDemo,
  CheckboxDemo,
  ComboboxDemo,
  DatePickerDemo,
  FormDemo,
  InputOTPDemo,
  ProgressDemo,
  RadioGroupDemo,
  SelectDemo,
  SliderDemo,
  SwitchDemo,
  TextareaDemo,
  ToggleDemo,
  ToggleGroupDemo,
} from "@www/components/demos/forms"
import {
  AlertDialogDemo,
  CommandDemo,
  ContextMenuDemo,
  DialogDemo,
  DrawerDemo,
  DropdownMenuDemo,
  HoverCardDemo,
  MenubarDemo,
  PopoverDemo,
  SheetDemo,
  SonnerDemo,
  TooltipDemo,
} from "@www/components/demos/overlays"
import {
  AccordionDemo,
  BreadcrumbDemo,
  CardDemo,
  CollapsibleDemo,
  PaginationDemo,
  ScrollAreaDemo,
  TableDemo,
  TabsDemo,
} from "@www/components/demos/structure"
import {
  CtaDemo,
  FaqDemo,
  FeaturesDemo,
  FooterDemo,
  HeroDemo,
  NavbarDemo,
  PricingDemo,
  StatsDemo,
  TestimonialsDemo,
} from "@www/components/demos/blocks"
import {
  AnimatedGradientDemo,
  CountUpDemo,
  FadeInDemo,
  MarqueeDemo,
  ShimmerDemo,
  TypewriterDemo,
} from "@www/components/demos/motion"

/** Registry item name → live demo rendered on its docs page. */
export const demos: Record<string, React.ComponentType> = {
  accordion: AccordionDemo,
  alert: AlertDemo,
  "alert-dialog": AlertDialogDemo,
  avatar: AvatarDemo,
  badge: BadgeDemo,
  breadcrumb: BreadcrumbDemo,
  button: ButtonDemo,
  calendar: CalendarDemo,
  card: CardDemo,
  checkbox: CheckboxDemo,
  collapsible: CollapsibleDemo,
  combobox: ComboboxDemo,
  command: CommandDemo,
  "context-menu": ContextMenuDemo,
  "date-picker": DatePickerDemo,
  dialog: DialogDemo,
  drawer: DrawerDemo,
  "dropdown-menu": DropdownMenuDemo,
  form: FormDemo,
  "hover-card": HoverCardDemo,
  input: InputDemo,
  "input-otp": InputOTPDemo,
  label: LabelDemo,
  menubar: MenubarDemo,
  pagination: PaginationDemo,
  popover: PopoverDemo,
  progress: ProgressDemo,
  "radio-group": RadioGroupDemo,
  "scroll-area": ScrollAreaDemo,
  select: SelectDemo,
  separator: SeparatorDemo,
  sheet: SheetDemo,
  skeleton: SkeletonDemo,
  slider: SliderDemo,
  sonner: SonnerDemo,
  switch: SwitchDemo,
  table: TableDemo,
  tabs: TabsDemo,
  textarea: TextareaDemo,
  toggle: ToggleDemo,
  "toggle-group": ToggleGroupDemo,
  tooltip: TooltipDemo,
}

/** Registry block name → live demo rendered full-width on its docs page. */
export const blockDemos: Record<string, React.ComponentType> = {
  cta: CtaDemo,
  faq: FaqDemo,
  features: FeaturesDemo,
  footer: FooterDemo,
  hero: HeroDemo,
  navbar: NavbarDemo,
  pricing: PricingDemo,
  stats: StatsDemo,
  testimonials: TestimonialsDemo,
}

/** Registry motion name → live demo rendered on its docs page. */
export const motionDemos: Record<string, React.ComponentType> = {
  "animated-gradient": AnimatedGradientDemo,
  "count-up": CountUpDemo,
  "fade-in": FadeInDemo,
  marquee: MarqueeDemo,
  shimmer: ShimmerDemo,
  typewriter: TypewriterDemo,
}
