import { promises as fs } from "node:fs"
import path from "node:path"

import { ROOT_THEME } from "./config"

import {
  getIconSet,
  hexToSeed,
  resolveTheme,
  themeDefinitionSchema,
  themeDefinitions,
  themeToCss,
  type ColorSeed,
  type RadiusScale,
  type ThemeDefinition,
} from "@lorre-blocks/tokens"

/**
 * `lorre.theme.json` — the custom-theme contract (Phase 7.3). An agent (or the
 * www Theme Studio) writes this file; `theme create` turns it into injected
 * CSS. The engine is bundled into the CLI, so generation is fully offline and
 * byte-identical to what the Studio previews.
 */

export const THEME_FILE = "lorre.theme.json"

export function themeFilePath(cwd: string): string {
  return path.join(cwd, THEME_FILE)
}

export async function readThemeFile(cwd: string): Promise<unknown | null> {
  try {
    const raw = await fs.readFile(themeFilePath(cwd), "utf8")
    return JSON.parse(raw)
  } catch {
    return null
  }
}

export async function writeThemeFile(
  cwd: string,
  def: ThemeDefinition
): Promise<void> {
  await fs.writeFile(
    themeFilePath(cwd),
    JSON.stringify(def, null, 2) + "\n",
    "utf8"
  )
}

/** Flat problem list (agent-iterable) or the validated definition. */
export function validateDefinition(data: unknown): {
  def: ThemeDefinition | null
  problems: string[]
} {
  const parsed = themeDefinitionSchema.safeParse(data)
  if (!parsed.success) {
    const problems = parsed.error.issues.map((issue) => {
      const at = issue.path.length > 0 ? `${issue.path.join(".")}: ` : ""
      return `${at}${issue.message}`
    })
    return { def: null, problems }
  }
  const def = parsed.data as ThemeDefinition
  if (def.extends && !BUILTIN_THEME_NAMES.includes(def.extends)) {
    return {
      def: null,
      problems: [
        `extends: unknown base theme "${def.extends}"; available: ${BUILTIN_THEME_NAMES.join(", ")}`,
      ],
    }
  }
  return { def, problems: [] }
}

export const BUILTIN_THEME_NAMES = themeDefinitions.map((t) => t.name)

/** Resolve + emit the Tailwind v4 theme block for a validated definition. */
export function definitionToCss(def: ThemeDefinition): string {
  return themeToCss(resolveTheme(def))
}

/**
 * Color input accepted on flags: a 6-digit hex ("#5B6CFF") or an OKLCH triple
 * "hue:chroma:lightness" ("262:0.21:0.55").
 */
export function parseColorInput(input: string): ColorSeed {
  const triple = input.match(/^(\d*\.?\d+):(\d*\.?\d+):(\d*\.?\d+)$/)
  if (triple) {
    return {
      hue: Number(triple[1]),
      chroma: Number(triple[2]),
      lightness: Number(triple[3]),
    }
  }
  return hexToSeed(input) // throws with a clear message on anything else
}

const RADIUS_PRESETS: Record<string, number> = {
  none: 0,
  sm: 0.25,
  md: 0.5,
  lg: 0.75,
  xl: 1,
}

/**
 * One radius input → the full scale, using the ratios the shipped themes
 * follow (sm = base/2, md = 0.75·base, lg = base, xl = 1.5·base, 2xl = 2·base).
 */
export function radiusFromInput(input: string): RadiusScale {
  let base: number
  if (input in RADIUS_PRESETS) {
    base = RADIUS_PRESETS[input]
  } else {
    const rem = input.match(/^(\d*\.?\d+)rem$/)
    if (!rem) {
      throw new Error(
        `--radius must be one of ${Object.keys(RADIUS_PRESETS).join("|")} or a rem value like "0.5rem", got "${input}"`
      )
    }
    base = Number(rem[1])
  }
  const r = (n: number) => `${Math.round(n * 10000) / 10000}rem`
  return {
    base: r(base),
    sm: r(base / 2),
    md: r(base * 0.75),
    lg: r(base),
    xl: r(base * 1.5),
    "2xl": r(base * 2),
  }
}

export interface ThemeCreateFlags {
  name?: string
  extends?: string
  accent?: string
  neutral?: string
  secondary?: string
  radius?: string
  fontSans?: string
  fontMono?: string
  typeBase?: string
  typeRatio?: number
  scaling?: number
  icons?: string
}

/** Fallback stacks appended after a flag-provided family. */
const SANS_FALLBACK = ["ui-sans-serif", "system-ui", "sans-serif"]
const MONO_FALLBACK = ["ui-monospace", "SFMono-Regular", "monospace"]

/**
 * Merge CLI flags over a base definition (from --from, or empty). Flags win.
 * Throws on unparseable flag values; schema validation happens after.
 */
export function applyFlags(
  base: Record<string, unknown>,
  flags: ThemeCreateFlags
): Record<string, unknown> {
  const def: Record<string, unknown> = structuredClone(base)

  if (flags.name) def.name = flags.name
  if (!def.name) def.name = "custom"
  if (flags.extends) def.extends = flags.extends
  if (!def.extends) def.extends = ROOT_THEME
  if (!def.description) {
    def.description = `Custom theme "${def.name}" generated by lorre-blocks theme create.`
  }

  const colors = { ...(def.colors as Record<string, unknown> | undefined) }
  if (flags.accent) colors.accent = parseColorInput(flags.accent)
  if (flags.neutral) colors.neutral = parseColorInput(flags.neutral)
  if (flags.secondary) colors.secondary = parseColorInput(flags.secondary)
  if (Object.keys(colors).length > 0) def.colors = colors

  if (flags.radius) def.radius = radiusFromInput(flags.radius)

  const typography = {
    ...(def.typography as Record<string, unknown> | undefined),
  }
  if (flags.fontSans) typography.fontSans = [flags.fontSans, ...SANS_FALLBACK]
  if (flags.fontMono) typography.fontMono = [flags.fontMono, ...MONO_FALLBACK]
  if (flags.typeBase !== undefined || flags.typeRatio !== undefined) {
    const existing = (typography.typeScale ?? {}) as Record<string, unknown>
    typography.typeScale = {
      base: flags.typeBase ?? existing.base ?? "1rem",
      ratio: flags.typeRatio ?? existing.ratio ?? 1.25,
      ...(existing.fluid !== undefined ? { fluid: existing.fluid } : {}),
    }
  }
  if (Object.keys(typography).length > 0) def.typography = typography

  if (flags.scaling !== undefined) {
    // Accept Radix-style percentages (90..150) and plain factors (0.9..1.5).
    const factor = flags.scaling > 10 ? flags.scaling / 100 : flags.scaling
    def.spacing = { scaling: Math.round(factor * 10000) / 10000 }
  }

  if (flags.icons) {
    const [set, style] = flags.icons.split(":")
    def.icons = style ? { set, style } : { set }
  }

  return def
}

/** npm package behind the definition's icon choice, if any. */
export function iconPackageFor(def: ThemeDefinition): string | null {
  if (!def.icons) return null
  return getIconSet(def.icons.set)?.package ?? null
}
