import type { RegistryItem } from "./src/schema"

export const registry: RegistryItem[] = [
  {
    name: "utils",
    type: "registry:lib",
    description: "cn() helper for merging Tailwind class names.",
    source: "shadcn",
    category: "lib",
    license: "MIT",
    tags: ["classnames", "tailwind", "helper"],
    dependencies: ["clsx", "tailwind-merge"],
    files: [{ path: "lib/utils.ts", type: "registry:lib" }],
  },
  {
    name: "button",
    type: "registry:ui",
    description:
      "Displays a button or a component that looks like a button. Supports variants, sizes, and asChild.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["button", "action", "form", "cta"],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/button.tsx", type: "registry:ui" }],
  },
  {
    name: "input",
    type: "registry:ui",
    description: "A styled text input field.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["input", "text", "form", "field"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/input.tsx", type: "registry:ui" }],
  },
  {
    name: "label",
    type: "registry:ui",
    description:
      "Accessible label for form controls, built on Radix Label. Pairs with input, checkbox, radio-group, switch and select.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["label", "form", "field", "accessibility"],
    dependencies: ["@radix-ui/react-label"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/label.tsx", type: "registry:ui" }],
  },
  {
    name: "separator",
    type: "registry:ui",
    description:
      "Visual divider between content, horizontal or vertical, built on Radix Separator.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["separator", "divider", "rule", "layout"],
    dependencies: ["@radix-ui/react-separator"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/separator.tsx", type: "registry:ui" }],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    description:
      "Checkbox control with checked, unchecked and indeterminate states, built on Radix Checkbox.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["checkbox", "form", "toggle", "boolean", "selection"],
    dependencies: ["@radix-ui/react-checkbox", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/checkbox.tsx", type: "registry:ui" }],
  },
  {
    name: "switch",
    type: "registry:ui",
    description:
      "On/off toggle switch for boolean settings, built on Radix Switch.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["switch", "toggle", "form", "boolean", "settings"],
    dependencies: ["@radix-ui/react-switch"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/switch.tsx", type: "registry:ui" }],
  },
  {
    name: "radio-group",
    type: "registry:ui",
    description:
      "Single-choice radio button group, built on Radix Radio Group. Use for 2-5 mutually exclusive options; use select for longer lists.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["radio", "radio-group", "form", "choice", "selection"],
    dependencies: ["@radix-ui/react-radio-group", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/radio-group.tsx", type: "registry:ui" }],
  },
  {
    name: "tabs",
    type: "registry:ui",
    description:
      "Tabbed interface for switching between panels of content, built on Radix Tabs.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["tabs", "navigation", "panels", "switcher"],
    dependencies: ["@radix-ui/react-tabs"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/tabs.tsx", type: "registry:ui" }],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    description:
      "Small text popup shown on hover/focus, built on Radix Tooltip. Requires wrapping the app (or subtree) in TooltipProvider.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["tooltip", "hint", "popup", "hover", "overlay"],
    dependencies: ["@radix-ui/react-tooltip"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/tooltip.tsx", type: "registry:ui" }],
  },
  {
    name: "accordion",
    type: "registry:ui",
    description:
      "Vertically stacked disclosure sections that expand and collapse, built on Radix Accordion. Common for FAQs and settings groups.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["accordion", "collapse", "disclosure", "faq", "expandable"],
    dependencies: ["@radix-ui/react-accordion", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/accordion.tsx", type: "registry:ui" }],
  },
  {
    name: "dialog",
    type: "registry:ui",
    description:
      "Modal dialog with overlay, title, description and close button, built on Radix Dialog. Use for confirmations, forms and focused tasks.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["dialog", "modal", "overlay", "popup", "confirmation"],
    dependencies: ["@radix-ui/react-dialog", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/dialog.tsx", type: "registry:ui" }],
  },
  {
    name: "popover",
    type: "registry:ui",
    description:
      "Floating panel anchored to a trigger, built on Radix Popover. Use for rich content; use tooltip for plain text hints.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["popover", "overlay", "panel", "floating", "anchor"],
    dependencies: ["@radix-ui/react-popover"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/popover.tsx", type: "registry:ui" }],
  },
  {
    name: "dropdown-menu",
    type: "registry:ui",
    description:
      "Menu of actions opened from a trigger, built on Radix Dropdown Menu. Supports groups, submenus, checkbox and radio items, and shortcuts.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["dropdown", "menu", "actions", "context", "overlay"],
    dependencies: ["@radix-ui/react-dropdown-menu", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/dropdown-menu.tsx", type: "registry:ui" }],
  },
  {
    name: "select",
    type: "registry:ui",
    description:
      "Styled select dropdown for choosing one option from a list, built on Radix Select. Use for 5+ options; use radio-group for short lists.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["select", "dropdown", "form", "options", "picker"],
    dependencies: ["@radix-ui/react-select", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/select.tsx", type: "registry:ui" }],
  },
]
