import type { RegistryItem } from "./src/schema"

export const registry: RegistryItem[] = [
  {
    name: "utils",
    type: "registry:lib",
    description: "cn() helper for merging Tailwind class names.",
    source: "shadcn",
    category: "lib",
    license: "MIT",
    tags: ["classnames", "tailwind", "helper"],
    dependencies: ["clsx", "tailwind-merge"],
    files: [{ path: "lib/utils.ts", type: "registry:lib" }],
  },
  {
    name: "button",
    type: "registry:ui",
    description:
      "Displays a button or a component that looks like a button. Supports variants, sizes, and asChild.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["button", "action", "form", "cta"],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/button.tsx", type: "registry:ui" }],
  },
  {
    name: "input",
    type: "registry:ui",
    description: "A styled text input field.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["input", "text", "form", "field"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/input.tsx", type: "registry:ui" }],
  },
  {
    name: "label",
    type: "registry:ui",
    description:
      "Accessible label for form controls, built on Radix Label. Pairs with input, checkbox, radio-group, switch and select.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["label", "form", "field", "accessibility"],
    dependencies: ["@radix-ui/react-label"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/label.tsx", type: "registry:ui" }],
  },
  {
    name: "separator",
    type: "registry:ui",
    description:
      "Visual divider between content, horizontal or vertical, built on Radix Separator.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["separator", "divider", "rule", "layout"],
    dependencies: ["@radix-ui/react-separator"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/separator.tsx", type: "registry:ui" }],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    description:
      "Checkbox control with checked, unchecked and indeterminate states, built on Radix Checkbox.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["checkbox", "form", "toggle", "boolean", "selection"],
    dependencies: ["@radix-ui/react-checkbox", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/checkbox.tsx", type: "registry:ui" }],
  },
  {
    name: "switch",
    type: "registry:ui",
    description:
      "On/off toggle switch for boolean settings, built on Radix Switch.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["switch", "toggle", "form", "boolean", "settings"],
    dependencies: ["@radix-ui/react-switch"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/switch.tsx", type: "registry:ui" }],
  },
  {
    name: "radio-group",
    type: "registry:ui",
    description:
      "Single-choice radio button group, built on Radix Radio Group. Use for 2-5 mutually exclusive options; use select for longer lists.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["radio", "radio-group", "form", "choice", "selection"],
    dependencies: ["@radix-ui/react-radio-group", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/radio-group.tsx", type: "registry:ui" }],
  },
  {
    name: "tabs",
    type: "registry:ui",
    description:
      "Tabbed interface for switching between panels of content, built on Radix Tabs.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["tabs", "navigation", "panels", "switcher"],
    dependencies: ["@radix-ui/react-tabs"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/tabs.tsx", type: "registry:ui" }],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    description:
      "Small text popup shown on hover/focus, built on Radix Tooltip. Requires wrapping the app (or subtree) in TooltipProvider.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["tooltip", "hint", "popup", "hover", "overlay"],
    dependencies: ["@radix-ui/react-tooltip"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/tooltip.tsx", type: "registry:ui" }],
  },
  {
    name: "accordion",
    type: "registry:ui",
    description:
      "Vertically stacked disclosure sections that expand and collapse, built on Radix Accordion. Common for FAQs and settings groups.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["accordion", "collapse", "disclosure", "faq", "expandable"],
    dependencies: ["@radix-ui/react-accordion", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/accordion.tsx", type: "registry:ui" }],
  },
  {
    name: "dialog",
    type: "registry:ui",
    description:
      "Modal dialog with overlay, title, description and close button, built on Radix Dialog. Use for confirmations, forms and focused tasks.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["dialog", "modal", "overlay", "popup", "confirmation"],
    dependencies: ["@radix-ui/react-dialog", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/dialog.tsx", type: "registry:ui" }],
  },
  {
    name: "popover",
    type: "registry:ui",
    description:
      "Floating panel anchored to a trigger, built on Radix Popover. Use for rich content; use tooltip for plain text hints.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["popover", "overlay", "panel", "floating", "anchor"],
    dependencies: ["@radix-ui/react-popover"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/popover.tsx", type: "registry:ui" }],
  },
  {
    name: "dropdown-menu",
    type: "registry:ui",
    description:
      "Menu of actions opened from a trigger, built on Radix Dropdown Menu. Supports groups, submenus, checkbox and radio items, and shortcuts.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["dropdown", "menu", "actions", "context", "overlay"],
    dependencies: ["@radix-ui/react-dropdown-menu", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/dropdown-menu.tsx", type: "registry:ui" }],
  },
  {
    name: "select",
    type: "registry:ui",
    description:
      "Styled select dropdown for choosing one option from a list, built on Radix Select. Use for 5+ options; use radio-group for short lists.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["select", "dropdown", "form", "options", "picker"],
    dependencies: ["@radix-ui/react-select", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/select.tsx", type: "registry:ui" }],
  },
  {
    name: "card",
    type: "registry:ui",
    description:
      "Surface container with header, title, description, content and footer sections. The base building block for dashboards.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["card", "container", "surface", "panel", "dashboard"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/card.tsx", type: "registry:ui" }],
  },
  {
    name: "badge",
    type: "registry:ui",
    description:
      "Small status descriptor with default/secondary/destructive/success/warning/outline variants.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["badge", "tag", "chip", "status", "label"],
    dependencies: ["class-variance-authority"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/badge.tsx", type: "registry:ui" }],
  },
  {
    name: "avatar",
    type: "registry:ui",
    description:
      "User avatar with image and automatic initials fallback, built on Radix Avatar.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["avatar", "user", "profile", "image", "fallback"],
    dependencies: ["@radix-ui/react-avatar"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/avatar.tsx", type: "registry:ui" }],
  },
  {
    name: "alert",
    type: "registry:ui",
    description:
      "Callout banner for inline messages with default/destructive/success/warning variants. For confirmations that need action, use alert-dialog.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["alert", "callout", "banner", "message", "notice"],
    dependencies: ["class-variance-authority"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/alert.tsx", type: "registry:ui" }],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    description:
      "Pulsing placeholder block shown while content loads. Size it with width/height utilities.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["skeleton", "loading", "placeholder", "shimmer"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/skeleton.tsx", type: "registry:ui" }],
  },
  {
    name: "table",
    type: "registry:ui",
    description:
      "Styled HTML table: header, body, footer, row, cell and caption parts with hover and selected states.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["table", "data", "grid", "rows", "columns"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/table.tsx", type: "registry:ui" }],
  },
  {
    name: "alert-dialog",
    type: "registry:ui",
    description:
      "Modal confirmation dialog that interrupts the user and requires an explicit Cancel/Action choice, built on Radix Alert Dialog. Buttons come from the button component.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["alert-dialog", "confirm", "modal", "destructive", "overlay"],
    dependencies: ["@radix-ui/react-alert-dialog"],
    registryDependencies: ["utils", "button"],
    files: [{ path: "ui/alert-dialog.tsx", type: "registry:ui" }],
  },
  {
    name: "sheet",
    type: "registry:ui",
    description:
      "Panel that slides in from any screen edge (top/bottom/left/right), built on Radix Dialog. Common for mobile navigation and side forms.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["sheet", "drawer", "sidebar", "slide", "overlay", "panel"],
    dependencies: [
      "@radix-ui/react-dialog",
      "class-variance-authority",
      "lucide-react",
    ],
    registryDependencies: ["utils"],
    files: [{ path: "ui/sheet.tsx", type: "registry:ui" }],
  },
  {
    name: "hover-card",
    type: "registry:ui",
    description:
      "Rich preview card shown when hovering a link or element, built on Radix Hover Card. For plain text hints use tooltip.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["hover-card", "preview", "popup", "hover", "overlay"],
    dependencies: ["@radix-ui/react-hover-card"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/hover-card.tsx", type: "registry:ui" }],
  },
  {
    name: "context-menu",
    type: "registry:ui",
    description:
      "Right-click menu with groups, submenus, checkbox and radio items, built on Radix Context Menu.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["context-menu", "right-click", "menu", "actions", "overlay"],
    dependencies: ["@radix-ui/react-context-menu", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/context-menu.tsx", type: "registry:ui" }],
  },
  {
    name: "sonner",
    type: "registry:ui",
    description:
      "Toast notification host built on sonner, styled with Lorre tokens. Render <Toaster /> once near the app root, then call toast() from anywhere.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["toast", "sonner", "notification", "snackbar", "feedback"],
    dependencies: ["sonner"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/sonner.tsx", type: "registry:ui" }],
  },
  {
    name: "toggle",
    type: "registry:ui",
    description:
      "Two-state button that can be on or off, built on Radix Toggle. Use for tool options like bold/italic; use switch for settings.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["toggle", "button", "pressed", "state", "toolbar"],
    dependencies: ["@radix-ui/react-toggle", "class-variance-authority"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/toggle.tsx", type: "registry:ui" }],
  },
  {
    name: "collapsible",
    type: "registry:ui",
    description:
      "Single expand/collapse region with a trigger, built on Radix Collapsible. For stacked sections use accordion.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["collapsible", "expand", "collapse", "disclosure", "toggle"],
    dependencies: ["@radix-ui/react-collapsible"],
    files: [{ path: "ui/collapsible.tsx", type: "registry:ui" }],
  },
  {
    name: "progress",
    type: "registry:ui",
    description:
      "Horizontal progress bar showing completion of a task, built on Radix Progress. For unknown durations use skeleton.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["progress", "bar", "loading", "percentage", "status"],
    dependencies: ["@radix-ui/react-progress"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/progress.tsx", type: "registry:ui" }],
  },
  {
    name: "slider",
    type: "registry:ui",
    description:
      "Draggable slider for selecting a value or range from a numeric scale, built on Radix Slider. Renders one thumb per value.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["slider", "range", "form", "numeric", "input"],
    dependencies: ["@radix-ui/react-slider"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/slider.tsx", type: "registry:ui" }],
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    description:
      "Hierarchical navigation trail with links, separators, ellipsis and current-page marker. Supports asChild for router links.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["breadcrumb", "navigation", "trail", "hierarchy", "path"],
    dependencies: ["@radix-ui/react-slot", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/breadcrumb.tsx", type: "registry:ui" }],
  },
  {
    name: "pagination",
    type: "registry:ui",
    description:
      "Page navigation with previous/next, numbered links and ellipsis. Links are styled via the button component's variants.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["pagination", "pages", "navigation", "next", "previous"],
    dependencies: ["lucide-react"],
    registryDependencies: ["utils", "button"],
    files: [{ path: "ui/pagination.tsx", type: "registry:ui" }],
  },
  {
    name: "command",
    type: "registry:ui",
    description:
      "Fast keyboard-driven command palette / filterable list built on cmdk. CommandDialog wraps it in a modal (⌘K pattern).",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["command", "palette", "cmdk", "search", "keyboard", "menu"],
    dependencies: ["cmdk", "lucide-react"],
    registryDependencies: ["utils", "dialog"],
    files: [{ path: "ui/command.tsx", type: "registry:ui" }],
  },
  {
    name: "combobox",
    type: "registry:ui",
    description:
      "Searchable single-select dropdown composed from popover + command + button. Pass options as {value,label}; controlled or uncontrolled.",
    source: "lorre",
    category: "component",
    tags: ["combobox", "autocomplete", "search", "select", "form", "picker"],
    dependencies: ["lucide-react"],
    registryDependencies: ["utils", "button", "command", "popover"],
    files: [{ path: "ui/combobox.tsx", type: "registry:ui" }],
  },
  {
    name: "form",
    type: "registry:ui",
    description:
      "Form primitives on react-hook-form: FormField/Item/Label/Control/Description/Message with wired aria attributes and error states. Bring your own resolver (e.g. zod).",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["form", "validation", "react-hook-form", "field", "error"],
    dependencies: ["react-hook-form", "@radix-ui/react-slot"],
    registryDependencies: ["utils", "label"],
    files: [{ path: "ui/form.tsx", type: "registry:ui" }],
  },
  {
    name: "calendar",
    type: "registry:ui",
    description:
      "Month calendar for picking dates, built on react-day-picker v10. Supports single, multiple and range modes; nav uses button variants.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["calendar", "date", "month", "day-picker", "form"],
    dependencies: ["react-day-picker", "lucide-react"],
    registryDependencies: ["utils", "button"],
    files: [{ path: "ui/calendar.tsx", type: "registry:ui" }],
  },
  {
    name: "date-picker",
    type: "registry:ui",
    description:
      "Single-date picker composed from popover + calendar + button, with locale-formatted trigger text. Controlled or uncontrolled.",
    source: "lorre",
    category: "component",
    tags: ["date-picker", "date", "calendar", "form", "picker"],
    dependencies: ["lucide-react"],
    registryDependencies: ["utils", "button", "calendar", "popover"],
    files: [{ path: "ui/date-picker.tsx", type: "registry:ui" }],
  },
  {
    name: "textarea",
    type: "registry:ui",
    description:
      "Multi-line text input field, styled to match input. Grows with rows/min-height utilities.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["textarea", "text", "form", "field", "multiline"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/textarea.tsx", type: "registry:ui" }],
  },
  {
    name: "input-otp",
    type: "registry:ui",
    description:
      "One-time-password / PIN input with individual character slots, fake caret and separator, built on input-otp.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["otp", "pin", "code", "verification", "form", "input"],
    dependencies: ["input-otp", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/input-otp.tsx", type: "registry:ui" }],
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    description:
      "Group of two-state toggle buttons with single or multiple selection, built on Radix Toggle Group. Items inherit variant/size from the group via the toggle component's variants.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["toggle-group", "toggle", "toolbar", "selection", "segmented"],
    dependencies: ["@radix-ui/react-toggle-group", "class-variance-authority"],
    registryDependencies: ["utils", "toggle"],
    files: [{ path: "ui/toggle-group.tsx", type: "registry:ui" }],
  },
  {
    name: "scroll-area",
    type: "registry:ui",
    description:
      "Scrollable region with styled custom scrollbars (vertical and horizontal), built on Radix Scroll Area.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["scroll-area", "scrollbar", "overflow", "scroll", "container"],
    dependencies: ["@radix-ui/react-scroll-area"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/scroll-area.tsx", type: "registry:ui" }],
  },
  {
    name: "drawer",
    type: "registry:ui",
    description:
      "Touch-friendly drawer that slides from any screen edge with drag-to-dismiss, built on vaul. Bottom drawers show a drag handle; for desktop side panels prefer sheet.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["drawer", "bottom-sheet", "mobile", "overlay", "panel", "swipe"],
    dependencies: ["vaul"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/drawer.tsx", type: "registry:ui" }],
  },
  {
    name: "menubar",
    type: "registry:ui",
    description:
      "Desktop-style horizontal menu bar (File/Edit/View pattern) with dropdown menus, submenus, checkbox and radio items, built on Radix Menubar.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["menubar", "menu", "navigation", "desktop", "toolbar", "actions"],
    dependencies: ["@radix-ui/react-menubar", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/menubar.tsx", type: "registry:ui" }],
  },
  {
    name: "hero",
    type: "registry:block",
    description:
      "Landing page hero section: eyebrow badge, headline, supporting copy and action buttons. Content is passed as serializable props (title, description, actions), centered or start-aligned.",
    source: "lorre",
    category: "block",
    tags: ["hero", "landing", "header", "marketing", "section", "cta"],
    dependencies: ["class-variance-authority"],
    registryDependencies: ["utils", "badge", "button"],
    files: [{ path: "blocks/hero.tsx", type: "registry:block" }],
  },
  {
    name: "pricing",
    type: "registry:block",
    description:
      "Pricing section: header plus a responsive grid of tier cards with feature checklists and CTA links. Tiers are data ({name, price, features, cta, highlighted?, badge?}); prices are free-form strings so Free/Custom work.",
    source: "lorre",
    category: "block",
    tags: ["pricing", "plans", "tiers", "marketing", "section", "billing"],
    dependencies: ["lucide-react"],
    registryDependencies: ["utils", "badge", "button", "card"],
    files: [{ path: "blocks/pricing.tsx", type: "registry:block" }],
  },
  {
    name: "faq",
    type: "registry:block",
    description:
      "FAQ section: header plus an accordion of question/answer pairs, one open at a time. Items are data ({question, answer}[]).",
    source: "lorre",
    category: "block",
    tags: ["faq", "questions", "accordion", "marketing", "section", "support"],
    registryDependencies: ["utils", "accordion"],
    files: [{ path: "blocks/faq.tsx", type: "registry:block" }],
  },
  {
    name: "cta",
    type: "registry:block",
    description:
      "Call-to-action banner: rounded panel with headline, supporting copy and action buttons. \"accent\" variant fills with the primary color, \"outline\" stays on the card surface — both resolve per theme.",
    source: "lorre",
    category: "block",
    tags: ["cta", "call-to-action", "banner", "marketing", "section", "conversion"],
    dependencies: ["class-variance-authority"],
    registryDependencies: ["utils", "button"],
    files: [{ path: "blocks/cta.tsx", type: "registry:block" }],
  },
  {
    name: "footer",
    type: "registry:block",
    description:
      "Site footer: brand with description, link groups in a responsive grid, and a bottom line with copyright and legal links. All content passed as serializable props.",
    source: "lorre",
    category: "block",
    tags: ["footer", "navigation", "links", "site", "section", "legal"],
    registryDependencies: ["utils", "separator"],
    files: [{ path: "blocks/footer.tsx", type: "registry:block" }],
  },
  {
    name: "features",
    type: "registry:block",
    description:
      "Feature grid section: header plus a responsive 2-4 column grid of feature entries ({title, description, icon?}). Use for product capabilities or benefit lists.",
    source: "lorre",
    category: "block",
    tags: ["features", "grid", "benefits", "capabilities", "marketing", "section"],
    registryDependencies: ["utils"],
    files: [{ path: "blocks/features.tsx", type: "registry:block" }],
  },
  {
    name: "testimonials",
    type: "registry:block",
    description:
      "Testimonials section: header plus a responsive grid of quote cards with author, role and avatar (image URL or initials fallback). Items are data ({quote, author, role?, avatar?}[]).",
    source: "lorre",
    category: "block",
    tags: ["testimonials", "quotes", "social-proof", "reviews", "marketing", "section"],
    registryDependencies: ["utils", "avatar", "card"],
    files: [{ path: "blocks/testimonials.tsx", type: "registry:block" }],
  },
  {
    name: "stats",
    type: "registry:block",
    description:
      "Stats band: a row of large key numbers with labels and optional descriptions. Values are free-form strings so percentages, counts and latencies all work.",
    source: "lorre",
    category: "block",
    tags: ["stats", "metrics", "numbers", "kpi", "marketing", "section"],
    registryDependencies: ["utils"],
    files: [{ path: "blocks/stats.tsx", type: "registry:block" }],
  },
  {
    name: "navbar",
    type: "registry:block",
    description:
      "Site header / navigation bar: brand, links, action buttons, and a mobile hamburger menu. Optionally sticky with a blur backdrop. Links and actions are data props; the mobile disclosure state is internal.",
    source: "lorre",
    category: "block",
    tags: ["navbar", "header", "navigation", "menu", "mobile", "site", "sticky"],
    dependencies: ["lucide-react", "class-variance-authority"],
    registryDependencies: ["utils", "button"],
    files: [{ path: "blocks/navbar.tsx", type: "registry:block" }],
  },
  {
    name: "marquee",
    type: "registry:motion",
    description:
      "Infinite horizontal scroll strip for logo clouds and tickers. Pure CSS (content rendered twice, -50% loop via the --animate-marquee token); pauseOnHover and reverse props; honors prefers-reduced-motion.",
    source: "lorre",
    category: "motion",
    tags: ["marquee", "ticker", "logo-cloud", "scroll", "animation", "motion"],
    registryDependencies: ["utils"],
    files: [{ path: "motion/marquee.tsx", type: "registry:motion" }],
  },
  {
    name: "count-up",
    type: "registry:motion",
    description:
      "Animated number that counts from 0 to a value with an ease-out curve when it enters the viewport. Locale-formatted with decimals/prefix/suffix; jumps straight to the value under prefers-reduced-motion. Pair with the stats block.",
    source: "lorre",
    category: "motion",
    tags: ["count-up", "counter", "number", "stats", "animation", "motion"],
    registryDependencies: ["utils"],
    files: [{ path: "motion/count-up.tsx", type: "registry:motion" }],
  },
  {
    name: "fade-in",
    type: "registry:motion",
    description:
      "Reveal-on-scroll wrapper: children fade and slide in the first time they enter the viewport. Duration rides the theme's --motion-duration-slow token; delay prop staggers siblings; motion-reduce disables the transition.",
    source: "lorre",
    category: "motion",
    tags: ["fade-in", "reveal", "scroll", "viewport", "animation", "motion", "stagger"],
    registryDependencies: ["utils"],
    files: [{ path: "motion/fade-in.tsx", type: "registry:motion" }],
  },
  {
    name: "typewriter",
    type: "registry:motion",
    description:
      "Types through a list of words character by character with a blinking caret (theme caret-blink token). Configurable typing/deleting speeds and pause; loops by default; prefers-reduced-motion renders the first word statically.",
    source: "lorre",
    category: "motion",
    tags: ["typewriter", "typing", "text", "hero", "animation", "motion"],
    registryDependencies: ["utils"],
    files: [{ path: "motion/typewriter.tsx", type: "registry:motion" }],
  },
  {
    name: "shimmer",
    type: "registry:motion",
    description:
      "Text with a highlight sweeping through it — pure CSS gradient clipped to the text, driven by the --animate-shimmer token. motion-reduce freezes it to plain muted text. For loading labels and subtle emphasis.",
    source: "lorre",
    category: "motion",
    tags: ["shimmer", "text", "loading", "skeleton", "animation", "motion"],
    registryDependencies: ["utils"],
    files: [{ path: "motion/shimmer.tsx", type: "registry:motion" }],
  },
  {
    name: "animated-gradient",
    type: "registry:motion",
    description:
      "Text filled with a slowly drifting gradient built from the theme accent scale (--primary to --accent-8), driven by the --animate-gradient token. Re-themes automatically; motion-reduce parks the gradient still.",
    source: "lorre",
    category: "motion",
    tags: ["gradient", "text", "hero", "accent", "animation", "motion"],
    registryDependencies: ["utils"],
    files: [{ path: "motion/animated-gradient.tsx", type: "registry:motion" }],
  },
  {
    name: "aspect-ratio",
    type: "registry:ui",
    description: "Displays content within a desired ratio.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["aspect-ratio", "media", "image", "video", "layout"],
    dependencies: ["@radix-ui/react-aspect-ratio"],
    files: [{ path: "ui/aspect-ratio.tsx", type: "registry:ui" }],
  },
  {
    name: "typography",
    type: "registry:ui",
    description:
      "shadcn's typography styles as components: headings, paragraph, blockquote, list, inline code, lead, large, small and muted — semantic HTML with Lorre token classes.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["typography", "prose", "heading", "text", "blockquote", "list"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/typography.tsx", type: "registry:ui" }],
  },
  {
    name: "carousel",
    type: "registry:ui",
    description:
      "A carousel with motion and swipe built on Embla. Horizontal or vertical, keyboard accessible, with Previous/Next controls and an api for dots/autoplay plugins.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["carousel", "slider", "swipe", "embla", "gallery"],
    dependencies: ["embla-carousel-react"],
    registryDependencies: ["utils", "button"],
    files: [{ path: "ui/carousel.tsx", type: "registry:ui" }],
  },
  {
    name: "chart",
    type: "registry:ui",
    description:
      "Recharts wrapper: ChartContainer with a config-driven color/label system (--color-<key> vars, light+dark), themed tooltip and legend. Compose any Recharts chart inside.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["chart", "graph", "recharts", "bar", "line", "area", "pie", "dashboard"],
    dependencies: ["recharts"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/chart.tsx", type: "registry:ui" }],
  },
  {
    name: "data-table",
    type: "registry:ui",
    description:
      "shadcn's data-table pattern as one generic component: TanStack Table v8 over the table primitives with sorting, filtering and optional pagination. Copy and specialize for bespoke tables.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["data-table", "table", "tanstack", "sorting", "pagination", "grid"],
    dependencies: ["@tanstack/react-table"],
    registryDependencies: ["utils", "table", "button"],
    files: [{ path: "ui/data-table.tsx", type: "registry:ui" }],
  },
  {
    name: "navigation-menu",
    type: "registry:ui",
    description:
      "A collection of links for navigating websites, with expandable content panels and a shared viewport. Radix Navigation Menu on Lorre tokens.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["navigation", "menu", "header", "links", "dropdown"],
    dependencies: [
      "@radix-ui/react-navigation-menu",
      "class-variance-authority",
      "lucide-react",
    ],
    registryDependencies: ["utils"],
    files: [{ path: "ui/navigation-menu.tsx", type: "registry:ui" }],
  },
  {
    name: "resizable",
    type: "registry:ui",
    description:
      "Accessible resizable panel groups and layouts with keyboard support, built on react-resizable-panels.",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["resizable", "panels", "split", "layout", "drag"],
    dependencies: ["react-resizable-panels", "lucide-react"],
    registryDependencies: ["utils"],
    files: [{ path: "ui/resizable.tsx", type: "registry:ui" }],
  },
  {
    name: "sidebar",
    type: "registry:ui",
    description:
      "A composable, themeable and customizable sidebar: provider with cookie-persisted state, Cmd/Ctrl+B toggle, offcanvas/icon/none collapse modes, floating and inset variants, mobile sheet, menus with badges, actions and skeletons. Rewired onto Lorre tokens (muted surface, accent hover).",
    source: "shadcn",
    category: "component",
    license: "MIT",
    tags: ["sidebar", "navigation", "layout", "shell", "dashboard", "collapsible"],
    dependencies: ["@radix-ui/react-slot", "class-variance-authority", "lucide-react"],
    registryDependencies: [
      "utils",
      "button",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "tooltip",
    ],
    files: [
      { path: "ui/sidebar.tsx", type: "registry:ui" },
      { path: "hooks/use-mobile.ts", type: "registry:hook" },
    ],
  },
]
